name: grimity
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  animations: ^2.0.11
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  flutter_animate: ^4.5.2
  flutter_layout_grid: ^2.0.8
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  fluttertoast: ^8.2.12
  gap: ^3.0.1
  mesh_gradient: ^1.3.8
  photo_manager: ^3.5.0
  skeletonizer: ^2.0.1
  custom_image_crop: ^0.1.1
  lottie: ^3.3.1
  photo_view: ^0.15.0
  readmore: ^3.0.0
  flutter_widget_from_html: ^0.17.0
  flutter_quill: ^11.4.2
  flutter_quill_delta_from_html: ^1.5.3
  vsc_quill_delta_to_html: ^1.0.5
  flutter_quill_extensions: ^11.0.0
  custom_refresh_indicator: ^4.0.1
  flutter_infinite_scroll_pagination: ^1.1.0

  # Annotation
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Database
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3

  # DI
  get_it: ^8.0.3
  injectable: ^2.5.0

  # Logger
  talker: ^4.7.1
  talker_dio_logger: ^4.7.1
  talker_flutter: ^4.7.1
  talker_riverpod_logger: ^4.7.1

  # Network
  dio: ^5.8.0+1
  mockito: ^5.4.5
  retrofit: ^4.4.2

  # Firebase
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  firebase_analytics: ^12.0.3

  # OAuth
  google_sign_in: ^6.3.0
  kakao_flutter_sdk_user: ^1.9.7+3

  # Routing
  go_router: ^15.1.1

  # State Management
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Utils
  collection: ^1.19.1
  device_info_plus: ^11.4.0
  flutter_gen: ^5.10.0
  flutter_image_compress: ^2.4.0
  flutter_native_splash: ^2.4.5
  intl: ^0.20.2
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  vector_graphics: ^1.1.18
  flutter_dotenv: ^5.2.1
  socket_io_client: ^3.1.2
  flutter_local_notifications: ^19.5.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_gen_runner: ^5.10.0
  freezed: ^3.0.4
  go_router_builder: ^2.8.2
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4
  retrofit_generator: ^9.1.9
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  git_config: ^1.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/icons/common/
    - assets/icons/drawer/
    - assets/icons/home/
    - assets/icons/main/
    - assets/icons/profile/
    - assets/icons/profile_edit/
    - assets/icons/drawer/
    - assets/icons/feed_upload/
    - assets/icons/editor/
    - assets/icons/refresh/
    - assets/icons/chat/
    - assets/icons/chat_message/
    - assets/view/
    - assets/images/
    - assets/images/sign_up/
    - assets/lottie/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
